apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: online-boutique
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: frontend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: checkoutservice-pdb
  namespace: online-boutique
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: checkoutservice
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cartservice-pdb
  namespace: online-boutique
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: cartservice
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: paymentservice-pdb
  namespace: online-boutique
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: paymentservice
